[package]
name = "model"
version = "0.1.0"
edition = "2024"

[lib]
name = "model"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
reqwest.workspace = true
rig-core.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true